package org.anonchatsecure.bramble.api.account;

import org.briarproject.nullsafety.NotNullByDefault;

import java.security.SecureRandom;

import javax.annotation.Nullable;

import static org.anonchatsecure.bramble.api.account.BackupConstants.RECOVERY_CODE_DIGITS;
import static org.anonchatsecure.bramble.api.account.BackupConstants.RECOVERY_CODE_GROUP_SIZE;

/**
 * The secret that protects a backup. It is generated by the app, shown once
 * and never stored on the device.
 */
@NotNullByDefault
public class RecoveryCode {

	/**
	 * Returns a new recovery code as a string of decimal digits.
	 */
	public static String generate(SecureRandom random) {
		StringBuilder sb = new StringBuilder(RECOVERY_CODE_DIGITS);
		for (int i = 0; i < RECOVERY_CODE_DIGITS; i++) {
			sb.append((char) ('0' + random.nextInt(10)));
		}
		return sb.toString();
	}

	/**
	 * Returns the given code split into groups for display.
	 */
	public static String format(String code) {
		StringBuilder sb = new StringBuilder();
		for (int i = 0; i < code.length(); i++) {
			if (i > 0 && i % RECOVERY_CODE_GROUP_SIZE == 0) sb.append(' ');
			sb.append(code.charAt(i));
		}
		return sb.toString();
	}

	/**
	 * Returns the given code as {@link BackupConstants#RECOVERY_CODE_DIGITS}
	 * ASCII digits, ignoring whitespace and dashes, or null if it is not a
	 * recovery code. Digits from other scripts are accepted.
	 */
	@Nullable
	public static String normalise(String code) {
		StringBuilder sb = new StringBuilder(RECOVERY_CODE_DIGITS);
		for (int i = 0; i < code.length(); i++) {
			char c = code.charAt(i);
			if (c == '-' || Character.isWhitespace(c)) continue;
			int digit = Character.digit(c, 10);
			if (digit == -1) return null;
			if (sb.length() == RECOVERY_CODE_DIGITS) return null;
			sb.append((char) ('0' + digit));
		}
		if (sb.length() != RECOVERY_CODE_DIGITS) return null;
		return sb.toString();
	}
}
